### ISSUE TITLE
嵌入Ant Design Pro ，MFSU阶段报错 Module not found: Error: Can't resolve '@antv/s2'

### ISSUE THREAD

**Issue by scarletfrank** [antvis/GraphInsight#64]
## 目标 

因为我现在项目是个稍微旧一点的Ant Design Pro版本，我只能新建一个试着搭配一下。目标是Ant Design Pro里打开一个页面，就是GraphInsight的页面。然后通过里面的Neo4j资产，对图数据库进行探索分析。

## 简要复现步骤

1. npm i @ant-design/pro-cli -g
2. pro create myapp （选umi@4）
3. npm i @antv/gi-theme-antd @antv/g6 @antv/gi-sdk @antv/gi-assets-tugraph @antv/gi-assets-neo4j @antv/gi-assets-graphscope @antv/gi-assets-advance @antv/gi-assets-basic @antv/gi-assets-scene @antv/graphin

我一开始是手动改package.json 再npm install，这一阶段都没遇到啥问题
```json

 "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.13",
    "@antv/g6": "^4.7.16",
    "@antv/gi-assets-advance": "^1.1.0",
    "@antv/gi-assets-basic": "^1.1.0",
    "@antv/gi-assets-graphscope": "^1.0.2",
    "@antv/gi-assets-neo4j": "^1.0.2",
    "@antv/gi-assets-scene": "^1.0.0",
    "@antv/gi-assets-tugraph": "^1.0.2",
    "@antv/gi-sdk": "^1.1.0",
    "@antv/gi-theme-antd": "^0.3.0",
    "@antv/graphin": "^2.7.13",
    "@umijs/route-utils": "^2.1.3",
    "antd": "^4.23.3",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.6.4",
    "rc-util": "^5.24.4",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.8.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.3.0"
  },
```

4. 配置对应路由和页面，就按CodeSandbox里的组件写法，npm run start

跳转到对应页面的时候，就会提示

```
MFSU compiled with 6 errors
    at /home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/preset-umi/dist/commands/dev/depBuildWorker/depBuilder.js:58:20
    at finalCallback (/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61916:32)
    at /home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61980:17
    at /home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:75765:3
    at Hook.eval [as callAsync] (eval at create (/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at Cache.storeBuildDependencies (/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:51434:37)
    at /home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61976:19
    at Hook.eval [as callAsync] (eval at create (/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:47:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
Module not found: Error: Can't resolve '@antv/s2-react' in '/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@antv/gi-assets-advance/es/components/TableMode'
Module not found: Error: Can't resolve '@antv/s2-react/dist/style.min.css' in '/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@antv/gi-assets-advance/es/components/TableMode'
Module not found: Error: Can't resolve '@antv/s2' in '/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@antv/gi-assets-advance/es/components/TableMode/hooks'
Module not found: Error: Can't resolve '@antv/s2' in '/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@antv/gi-assets-advance/es/components/TableMode/hooks'
Module not found: Error: Can't resolve '@antv/s2' in '/home/scarlet/GitHub/antd-gisdk-demo/node_modules/@antv/gi-assets-advance/es/components/TableMode/hooks'
```

## 尝试

 我尝试过安装 @antv/s2 和 @antv/s2-react，但没有起作用。后面搜了下资料，是不是这两个包应该是 @antv/gi-assets-advance的依赖呢？

**Comment by pomelo-nwu** [comment]
@scarletfrank 看报错应该是 advance 的资产包没写s2这个依赖，你手动安装下

**Comment by scarletfrank** [comment]
> @scarletfrank 看报错应该是 advance 的资产包没写s2这个依赖，你手动安装下

嗯，应该算是解决了。

1. 到advance资产包目录（`node_modules/@antv/gi-assets-advance/`）下执行了 npm i @antv/s2 @antv/s2-react
2. `GI_EXPORT_FILES.ts` 最后一行，给light加了引号

```
 export const THEME_VALUE = 'light';
```

然后就能正常看到GI页面了，不过我在想这个连图数据库的资产怎么调出来

**Comment by pomelo-nwu** [comment]
@scarletfrank 如果是Neo4j数据库，那么你再`import @antv/gi-assets-neo4j` 就可以了，这块文档确实，你稍微看下源码哈：https://github.com/antvis/GraphInsight/blob/master/packages/gi-assets-neo4j/src/services/CypherQuery.ts#L11

**Comment by scarletfrank** [comment]
> @scarletfrank 如果是Neo4j数据库，那么你再`import @antv/gi-assets-neo4j` 就可以了，这块文档缺失（近期内部需求太忙了，后面我有空整理下），你稍微看下源码哈：https://github.com/antvis/GraphInsight/blob/master/packages/gi-assets-neo4j/src/services/CypherQuery.ts#L11

嗯嗯，我自己研究下
